# Generated by Django 5.0.6 on 2026-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
                'ordering': ('name',),
            },
        ),
    ]
